<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        

    <!-- Scripts -->
    <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    <style>
        @media (min-width: 979px) {
            ul.nav li.dropdown:hover>ul.dropdown-menu {
                display: block;
            }
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28"
                        alt="Zend Framework <?= \Application\Module::VERSION ?>" />&nbsp;Skeleton Application
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" id="dropdownMenu1" data-toggle="dropdown">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="<?= $this->url('album') ?>">Albums</a></li>
                            <li><a href="album/text">Long text</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" id="dropdownMenu2" data-toggle="dropdown">
                            About Us
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMen2">
                            <li><a href="#">Abiut</a></li>
                            <li><a href="#">USUSU</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
            </div>
            </ul>
        </div>
        </div>
    </nav>
    <div class="container-fluid">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
</body>

</html>